// Optional browser regression: NODE_PATH=<Playwright module root> node tests/preview_browser.cjs
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const os=require('node:os');
const {pathToFileURL}=require('node:url');
const {execFileSync}=require('node:child_process');
const root=path.resolve(__dirname,'..');
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'covercraft-review-test-'));
const errors=[];
let browser;
function fixture(name,files,extra=[]) {
  const out=path.join(temp,name);
  const args=[path.join(root,'scripts/preview_feed.py')];
  files.forEach(f=>args.push('--image',path.join(temp,f)));
  execFileSync('python3',[...args,...extra,'--out-dir',out]);
  return pathToFileURL(path.join(out,'feed-preview.html')).href;
}
async function draw(page,x,y,w,h) {
  const b=await page.locator('#review-stage').boundingBox();
  await page.mouse.move(b.x+b.width*x,b.y+b.height*y);await page.mouse.down();
  await page.mouse.move(b.x+b.width*(x+w),b.y+b.height*(y+h),{steps:5});await page.mouse.up();
}
async function download(page,id,name) {
  const pending=page.waitForEvent('download');await page.locator(id).click();
  const d=await pending;const dest=path.join(temp,name);await d.saveAs(dest);return dest;
}
(async()=>{
  execFileSync('python3',['-c',`from PIL import Image\nfrom pathlib import Path\np=Path(${JSON.stringify(temp)})\nImage.new('RGB',(640,360),'#c89162').save(p/'before.png')\nImage.new('RGB',(1280,720),'#286350').save(p/'after.png')\nImage.new('RGB',(300,400),'#4a69a0').save(p/'portrait.png')`]);
  const pair=fixture('pair',['before.png','after.png']),single=fixture('single',['before.png']),mixed=fixture('mixed',['before.png','portrait.png']);
  browser=await chromium.launch({channel:'chrome',headless:true});
  const context=await browser.newContext({viewport:{width:1440,height:1100},offline:true});
  const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
  await page.goto(pair);await page.locator('[data-tab="review"]').click();
  await page.locator('#review-img').evaluate(img=>img.decode());
  await draw(page,.1,.12,.4,.3);
  await page.locator('#note-action').selectOption('reduce');
  await page.locator('#note-observation').fill('右上角装饰抢眼');
  await page.locator('#note-instruction').fill('弱化装饰，保留主标题');
  await page.locator('#note-form button[type=submit]').click();
  assert.equal(await page.locator('#note-list .note').count(),1);
  let savedPath=await download(page,'#export-json','first.json');
  let exported=JSON.parse(fs.readFileSync(savedPath));
  assert.equal(exported.images[0].notes[0].action,'reduce');
  assert.ok(Math.abs(exported.images[0].notes[0].rect.x-.1)<.005);
  assert.ok(Math.abs(exported.images[0].notes[0].rect.h-.3)<.005);
  await page.reload();await page.locator('[data-tab="review"]').click();
  assert.equal(await page.locator('#note-list .note').count(),1);
  console.log('PASS: region coordinates, JSON export and reload persistence');

  await page.locator('#grayscale').check();
  await page.locator('#blur').fill('3');
  assert.match(await page.locator('#review-img').evaluate(n=>n.style.filter),/grayscale\(1\).*blur\(3px\)/);
  await page.locator('#draw-mode').selectOption('mask');await draw(page,.7,.1,.2,.2);
  assert.equal(await page.locator('.region.mask').count(),1);
  await page.locator('#draw-mode').selectOption('focus');await draw(page,.2,.55,.5,.3);
  assert.equal(await page.locator('.region.focus').count(),1);
  const peek=await page.locator('#peek').boundingBox();await page.mouse.move(peek.x+8,peek.y+8);await page.mouse.down();
  assert.equal(await page.locator('#review-img').evaluate(n=>n.style.filter),'none');
  await page.mouse.move(10,10);await page.mouse.up();
  assert.match(await page.locator('#review-img').evaluate(n=>n.style.filter),/grayscale\(1\)/);
  await page.locator('#reset-diagnostics').click();assert.equal(await page.locator('.region.mask,.region.focus').count(),0);
  assert.equal(await page.locator('#note-list .note').count(),1);
  console.log('PASS: grayscale, blur, masks, focus, press-to-peek and reset preserves notes');

  await page.locator('#new-note').click();await page.locator('#note-action').selectOption('preserve');
  await page.locator('#note-instruction').fill('保持主标题逐字不变 <img src=x onerror=alert(1)>');
  await page.locator('#note-form button[type=submit]').click();
  assert.equal(await page.locator('#note-list img').count(),0);
  const md=fs.readFileSync(await download(page,'#export-md','brief.md'),'utf8');
  assert.ok(md.indexOf('保持主标题逐字不变')<md.indexOf('弱化装饰'));
  await page.locator('[data-tab="compare"]').click();await page.locator('#compare-mode').selectOption('wipe');
  await page.locator('#wipe').fill('72');
  assert.match(await page.locator('.compare-wipe .after').evaluate(n=>n.style.clipPath),/28%/);
  await page.locator('#compare-notes .note').first().getByRole('button',{name:'已解决 / 已保留',exact:true}).click();
  savedPath=await download(page,'#export-json','reviewed.json');exported=JSON.parse(fs.readFileSync(savedPath));
  assert.equal(exported.images[0].notes[0].verifications[exported.images[1].image_sha256].status,'resolved');
  await page.locator('#compare-after').selectOption('0');
  assert.ok(await page.locator('#compare-notes .note button').first().isDisabled());
  await page.locator('[data-tab="review"]').click();await page.locator('#note-list .note').first().getByRole('button',{name:'定位 / 编辑'}).click();
  await page.locator('#note-instruction').fill('进一步减弱装饰');await page.locator('#note-form button[type=submit]').click();
  const changed=JSON.parse(fs.readFileSync(await download(page,'#export-json','changed.json')));
  assert.deepEqual(changed.images[0].notes[0].verifications,{});
  console.log('PASS: literal text, preservation-first brief, wipe, image-specific verdicts and invalidation after edits');

  const fresh=await browser.newContext({offline:true,viewport:{width:1200,height:900}}),importPage=await fresh.newPage();importPage.on('pageerror',e=>errors.push(e.message));
  await importPage.goto(pair);await importPage.locator('#import-json').setInputFiles(savedPath);
  await importPage.locator('[data-tab="review"]').click();
  assert.equal(await importPage.locator('#note-list .note').count(),2);
  await importPage.locator('#import-json').setInputFiles(savedPath);assert.equal(await importPage.locator('#note-list .note').count(),2);
  const malformed=JSON.parse(fs.readFileSync(savedPath));malformed.images[0].notes[0].rect.w=2;
  const bad=path.join(temp,'malformed.json');fs.writeFileSync(bad,JSON.stringify(malformed));
  await importPage.locator('#import-json').setInputFiles(bad);
  await importPage.waitForFunction(()=>document.querySelector('#notice').textContent.startsWith('未导入'));
  assert.equal(await importPage.locator('#note-list .note').count(),2);
  const embedded=fixture('embedded',['before.png','after.png'],['--feedback',savedPath]);
  const embeddedContext=await browser.newContext({offline:true});const embeddedPage=await embeddedContext.newPage();
  await embeddedPage.goto(embedded);await embeddedPage.locator('[data-tab="review"]').click();
  assert.equal(await embeddedPage.locator('#note-list .note').count(),2);
  console.log('PASS: fresh import, duplicate import, invalid import leaves state intact, generator embeds feedback');

  const revision=fixture('revision',['before.png','after.png'],['--feedback',savedPath,'--current-image',path.join(temp,'after.png'),'--previous-image',path.join(temp,'before.png')]);
  const revisionContext=await browser.newContext({offline:true,viewport:{width:1280,height:1000}}),revisionPage=await revisionContext.newPage();
  revisionPage.on('pageerror',e=>errors.push(e.message));
  await revisionPage.goto(revision);
  assert.ok(await revisionPage.locator('#panel-review').isVisible());
  assert.equal(await revisionPage.locator('#review-image').inputValue(),'1');
  assert.equal(await revisionPage.locator('#note-list .note').count(),0);
  assert.ok(await revisionPage.locator('#copy-brief').isDisabled());
  assert.match(await revisionPage.locator('#review-img').getAttribute('src'),/cover-02/);
  await revisionPage.locator('[data-tab="compare"]').click();
  assert.equal(await revisionPage.locator('#compare-before').inputValue(),'0');
  assert.equal(await revisionPage.locator('#compare-after').inputValue(),'1');
  assert.equal(await revisionPage.locator('#compare-notes .note').count(),2);
  await revisionPage.locator('#annotate-after').click();
  await draw(revisionPage,.2,.15,.25,.35);
  await revisionPage.locator('#note-instruction').fill('本轮只调整新版右侧画面');
  await revisionPage.locator('#note-form button[type=submit]').click();
  const revisionBrief=fs.readFileSync(await download(revisionPage,'#export-md','revision-brief.md'),'utf8');
  assert.ok(revisionBrief.includes('本轮只调整新版右侧画面'));
  assert.ok(revisionBrief.includes(exported.images[1].image_sha256));
  assert.ok(!revisionBrief.includes(exported.images[0].image_sha256));
  assert.ok(!revisionBrief.includes('弱化装饰'));
  assert.ok(!revisionBrief.includes('保持主标题逐字不变'));
  const allBackup=JSON.parse(fs.readFileSync(await download(revisionPage,'#export-json','all-rounds.json')));
  assert.equal(allBackup.images[0].notes.length,2);
  assert.equal(allBackup.images[1].notes.length,1);
  assert.equal(allBackup.active_image_sha256,exported.images[1].image_sha256);
  await revisionPage.reload();
  assert.equal(await revisionPage.locator('#review-image').inputValue(),'1');
  assert.equal(await revisionPage.locator('#note-list .note').count(),1);
  await revisionPage.locator('#review-image').selectOption('0');
  assert.ok(await revisionPage.locator('#back-current').isVisible());
  assert.match(await revisionPage.locator('#review-target-message').textContent(),/历史版本/);
  await revisionPage.locator('#back-current').click();
  assert.equal(await revisionPage.locator('#review-image').inputValue(),'1');
  assert.equal(await revisionPage.locator('#note-list .note').count(),1);
  console.log('PASS: opens latest revision, old notes remain in comparison, new annotations/export use only new image, full backup retains history, reload and return-current work');

  const reversed=fixture('reversed',['after.png','before.png'],['--feedback',savedPath,'--current-image',path.join(temp,'after.png'),'--previous-image',path.join(temp,'before.png')]);
  await revisionPage.goto(reversed);
  assert.equal(await revisionPage.locator('#review-image').inputValue(),'0');
  assert.equal(await revisionPage.locator('#compare-before').inputValue(),'1');
  assert.equal(await revisionPage.locator('#compare-after').inputValue(),'0');
  console.log('PASS: explicit revision roles work with reversed input order');

  await page.goto(mixed);await page.locator('[data-tab="compare"]').click();
  assert.ok(await page.locator('#compare-mode option[value=wipe]').evaluate(n=>n.disabled));
  assert.equal(await page.locator('.compare-side img').count(),2);
  await page.goto(single);await page.locator('[data-tab="compare"]').click();
  assert.match(await page.locator('#compare-hint').textContent(),/同一张图片/);
  await page.setViewportSize({width:390,height:844});await page.locator('[data-tab="review"]').click();
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
  await draw(page,.15,.2,.4,.3);await page.locator('#note-instruction').fill('手机端批注');await page.locator('#note-form button[type=submit]').click();
  assert.ok((await page.locator('#note-list').textContent()).includes('手机端批注'));
  assert.deepEqual(errors,[]);
  console.log('PASS: different aspect ratios, single image, mobile layout and drawing; no browser errors');
  await browser.close();browser=null;
  fs.rmSync(temp,{recursive:true,force:true});
  console.log('All browser checks passed.');
})().catch(async e=>{console.error(e);if(browser)await browser.close();console.error('Fixtures retained:',temp);process.exitCode=1;});
